repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
# -   repo: local
#     hooks:
#     -   id: pylint
#         # must be run in pipenv
#         name: pylint
#         entry: pylint
#         language: system
#         types: [python]
#         args:
#           [
#             "-rn", # Only display messages
#             "-sn", # Don't display the score
#           ]
