# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
    - name: "Upgrade pip"
      run: |
        python -m pip install --upgrade pip
    - name: Get pip cache dir
      id: get-pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"
    - name: pip cache
      uses: actions/cache@v3
      with:
        path: ${{ steps.get-pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: "Set up Python ${{ matrix.python-version }}"
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: "Install dependencies"
      run: |
        python -m pip install pipenv
        pipenv install --dev
    - name: "run pre-commit"
      run: |
        pipenv run pre-commit run --all --verbose
    - name: "run unit tests and gather coverage"
      run: |
        pipenv run pytest --cov=bbtq bbtq/tests/ -v
    - uses: codecov/codecov-action@v1
      with:
        files:  .coverage
        fail_ci_if_error: true
        verbose: false
